version: 2

updates:
# keep up to date the github actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    timezone: Europe/Rome
  groups:
    minor-actions-dependencies:
      update-types:
      - minor
      - patch
  commit-message:
    include: scope
    prefix: ci

# keep up to date the base docker image
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: build

# enable go dependencies security updates
- directory: /
  open-pull-requests-limit: 0
  package-ecosystem: gomod
  rebase-strategy: auto
  schedule:
    interval: daily
    time: "07:00"
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: chore

# keep up to date devcontainers
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Rome
  commit-message:
    include: scope
    prefix: build
