name: Security
on:
  pull_request:
    types: [opened]
  push:
env:
  CONTAINER_TAR: "container.tar"
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - name: "Build container"
        run: |
          docker build -t rond-security-check .
      - name: "Save container to tar"
        run: |
          docker save rond-security-check > $CONTAINER_TAR
      - name: Jetstack Paranoia
        uses: jetstack/paranoia@v0.2.1
        with:
          config: .paranoia.yml
          action: validate
          target_tar: file://${{ env.CONTAINER_TAR }}
