on:
  pull_request:
    types: [opened]
  push:
env:
  CONTAINER_TAR: "container.tar"

name: Security
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        show-progress: false
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
  paranoia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: "Build container"
        run: |
          docker build -t rond-security-check .
      - name: "Save container to tar"
        run: |
          docker save rond-security-check > $CONTAINER_TAR
      - name: Jetstack Paranoia
        uses: jetstack/paranoia@v0.2.1
        with:
          config: .paranoia.yml
          permissive: true # TODO: understand actually needed certificate and make this false
          target_tar: file://${{ env.CONTAINER_TAR }}
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with:
        show-progress: false
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
